format = """
$character
"""

# These values are displayed in tmux status bar
# [($memory_usage)](bold bright-green)\
# [(${custom.disk_space})](bold bright-blue) \

right_format = """
[($status)](bold bright-red)
[($cmd_duration)](bold bright-blue) \
$sudo$jobs
[❮](#a3aed2)
"""

# Disable the blank line at the start of the prompt
add_newline = false
command_timeout = 3000

[fill]
symbol = ' '
style = 'bold green'

[cmd_duration]
min_time = 500
style = 'bg:bright-blue'
format = '[$duration]($style)'

[memory_usage]
disabled = false
threshold = -1
format ='[${ram}]($style)'
style = 'bg:bright-green'

[status]
disabled = false
style = "bg:bright-red"
format = "[$symbol$status( 飯$signal_name)]($style)"
symbol = ""
not_executable_symbol = ""
not_found_symbol = ""
sigint_symbol = "ﰸ"
signal_symbol = "⚡"
map_symbol = true
pipestatus = true
pipestatus_separator = "|"
pipestatus_segment_format = "$symbol$status( 飯$signal_name)"
pipestatus_format ='[\[$pipestatus\]]($style)'

[sudo]
style = 'bold green'
format = '[$symbol]($style) '
symbol = ''
disabled = false

[custom.disk_space]
description = "Display free disk space"
# Percent sign needs to be removed from the output of the command (zsh)
# See: https://github.com/starship/starship/issues/3222
# command = "df -h / --output=avail,pcent | sed -e 1d | head -1 | awk '$1=$1'" # This won't work
# command = "df -h / --output=avail,pcent | sed -e 1d | head -1 | awk '$1=$1' | sed 's/%//'"
# format = "[$output%]($style)"
command = "df -h / --output=avail | sed -e 1d | head -1 | awk '$1=$1'"
when = true
format = "[$output]($style)"
style = "fg:black bg:bright-blue"

[custom.zsh_escape]
command = "printf '%s' '%_∙'" # shows output of command
shell = "zsh"
when = true
format = "[$output ]($style)"
style = "bright-black"
