name: Buildroot

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      
      - name: Build with buildroot
        run: |
          git clone https://gitlab.com/buildroot.org/buildroot.git
          cd buildroot
          git checkout -b tag_2025_02_4 tags/2025.02.4
          make BR2_EXTERNAL=../builders/buildroot-zynq-zed-xhci defconfig BR2_DEFCONFIG=../builders/buildroot-zynq-zed-xhci/configs/zynq-zed-xhci_defconfig O=../output-buildroot-zynq-zed-xhci
          cd ../output-buildroot-zynq-zed-xhci
          make -j $(nproc)
          gzip -k --force images/rootfs.ext2

      - uses: actions/upload-artifact@v4
        with:
          name: buildroot-binaries
          path: |
            output-buildroot-zynq-zed-xhci/build/linux-custom/vmlinux
            output-buildroot-zynq-zed-xhci/images/rootfs.ext2.gz
            output-buildroot-zynq-zed-xhci/images/zynq-zed-xhci.dtb
            buildroot/dl/linux/xlnx_rebase_*.tar.gz
