name: NuttX

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Install custom toolchains
        run: |

          # https://toolchains.bootlin.com
          wget https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--glibc--bleeding-edge-2025.08-1.tar.xz
          tar xf aarch64--glibc--bleeding-edge-2025.08-1.tar.xz
          # CROSS_COMPILE prefix: $GITHUB_WORKSPACE/aarch64--glibc--bleeding-edge-2025.08-1/bin/aarch64-buildroot-linux-gnu-
          wget https://toolchains.bootlin.com/downloads/releases/toolchains/armv6-eabihf/tarballs/armv6-eabihf--glibc--bleeding-edge-2025.08-1.tar.xz
          tar xf armv6-eabihf--glibc--bleeding-edge-2025.08-1.tar.xz
          # CROSS_COMPILE prefix: $GITHUB_WORKSPACE/armv6-eabihf--glibc--bleeding-edge-2025.08-1/bin/arm-buildroot-linux-gnueabihf-

      - name: Download NuttX
        run: |

          # https://nuttx.apache.org/docs/latest/quickstart/install.html#download-nuttx
          mkdir nuttxspace
          cd nuttxspace
          curl -L https://github.com/apache/nuttx/tarball/master -o nuttx.tar.gz
          curl -L https://github.com/apache/nuttx-apps/tarball/master -o apps.tar.gz
          tar zxf nuttx.tar.gz --one-top-level=nuttx --strip-components 1
          tar zxf apps.tar.gz --one-top-level=apps --strip-components 1
          
      - name: Setup NuttX
        run: |

          sudo apt-get -yq update
          # https://nuttx.apache.org/docs/latest/quickstart/install.html#prerequisites
          sudo apt-get -yq install \
          bison flex gettext texinfo libncurses5-dev libncursesw5-dev xxd \
          git gperf automake libtool pkg-config build-essential gperf genromfs \
          libgmp-dev libmpc-dev libmpfr-dev libisl-dev binutils-dev libelf-dev \
          libexpat1-dev gcc-multilib g++-multilib picocom u-boot-tools util-linux
          # https://nuttx.apache.org/docs/latest/quickstart/install.html#kconfig-frontend
          sudo apt-get -yq install kconfig-frontends

        # Extra dependencies specific to particular demos.
      - name: Install extra dependencies
        run: |

          # sim/alsa - https://github.com/apache/nuttx/pull/15918
          # https://github.com/apache/nuttx/blob/a84d263f094afc72a545d0cfcead88fd498947bf/tools/ci/docker/linux/Dockerfile#L335-L381
          sudo apt-get -yq install --no-install-recommends \
            genromfs \
            gettext \
            lib32z1-dev \
            libasound2-dev \
            libcurl4-openssl-dev \
            libmp3lame-dev \
            libmad0-dev \
            libncurses5-dev \
            libpulse-dev \
            libtinfo6 \
            libusb-1.0-0-dev \
            libv4l-dev \
            libx11-dev \
            libxext-dev \
            linux-headers-generic \
            u-boot-tools \
            xxd \
            subversion \
            tclsh

      - name: Build NuttX examples for aarch64
        run: |

          cd nuttxspace/nuttx

          # https://github.com/apache/nuttx/blob/eea9d15b4194a76e1aeaebf7f2d41cac2530cd2a/boards/sim/sim/sim/scripts/Make.defs#L155-L156
          sed -i -e 's/ARCHCFLAGS += -mcmodel=medium/ARCHCFLAGS += -mcmodel=small/g' boards/sim/sim/sim/scripts/Make.defs
          sed -i -e 's/ARCHCXXFLAGS += -mcmodel=medium/ARCHCXXFLAGS += -mcmodel=small/g' boards/sim/sim/sim/scripts/Make.defs

          for f in boards/sim/sim/sim/configs/*;
          do
            config=$(basename $f)

            [[ "$config" == "alsa" ]] && continue
            [[ "$config" == "citest" ]] && continue
            [[ "$config" == "crypto" ]] && continue
            [[ "$config" == "dynconns" ]] && continue
            [[ "$config" == "minmea" ]] && continue
            [[ "$config" == "module32" ]] && continue
            [[ "$config" == "nxcamera" ]] && continue
            [[ "$config" == "posix_spawn" ]] && continue
            [[ "$config" == "posix_test" ]] && continue
            [[ "$config" == "rpproxy" ]] && continue
            [[ "$config" == "rpserver" ]] && continue
            [[ "$config" == "sotest32" ]] && continue
            [[ "$config" == "wamr" ]] && continue
            [[ "$config" == "windows" ]] && continue
            [[ "$config" == "windows64" ]] && continue

            # https://github.com/apache/nuttx/issues/18057#issuecomment-3790310667
            [[ "$config" == "adb" ]] && continue
            [[ "$config" == "rpproxy_uart" ]] && continue
            [[ "$config" == "rpproxy_virtio" ]] && continue
            [[ "$config" == "rtptools" ]] && continue
            [[ "$config" == "tcpblaster" ]] && continue
            [[ "$config" == "vncserver" ]] && continue
            [[ "$config" == "wakaama" ]] && continue

            echo "Building SIM config $config"

            make distclean
            ./tools/configure.sh sim:$config
            kconfig-tweak --disable CONFIG_HOST_X86
            kconfig-tweak --disable CONFIG_HOST_X86_64
            kconfig-tweak --enable CONFIG_HOST_ARM64
            make -j 2 CROSSDEV=$GITHUB_WORKSPACE/aarch64--glibc--bleeding-edge-2025.08-1/bin/aarch64-buildroot-linux-gnu-
            mkdir -p build/sim/aarch64/$config
            mv nuttx nuttx.tgz build/sim/aarch64/$config
          done

      - name: Build NuttX examples for x86_64
        run: |

          cd nuttxspace/nuttx

          for f in boards/sim/sim/sim/configs/*;
          do
            config=$(basename $f)

            [[ "$config" == "alsa" ]] && continue
            [[ "$config" == "citest" ]] && continue
            [[ "$config" == "crypto" ]] && continue
            [[ "$config" == "dynconns" ]] && continue
            [[ "$config" == "minmea" ]] && continue
            [[ "$config" == "module32" ]] && continue
            [[ "$config" == "nxcamera" ]] && continue
            [[ "$config" == "posix_spawn" ]] && continue
            [[ "$config" == "posix_test" ]] && continue
            [[ "$config" == "rpproxy" ]] && continue
            [[ "$config" == "rpserver" ]] && continue
            [[ "$config" == "sotest32" ]] && continue
            [[ "$config" == "wamr" ]] && continue
            [[ "$config" == "windows" ]] && continue
            [[ "$config" == "windows64" ]] && continue

            echo "Building SIM config $config"

            make distclean
            ./tools/configure.sh sim:$config
            make -j 2
            mkdir -p build/sim/x86_64/$config
            mv nuttx nuttx.tgz build/sim/x86_64/$config
          done

      - uses: actions/upload-artifact@v4
        with:
          name: nuttx-binaries
          # Maintain path hierarchy https://github.com/actions/upload-artifact/issues/174#issuecomment-2649189928
          path: |
            nuttxspace/nuttx/build/
            nuttxspace/nuttx/.gitignore
