name: NuttX

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Print apt sources
        run: |

          cat /etc/apt/sources.list.d/ubuntu.sources

        # https://github.com/actions/runner-images/issues/10901
        # https://github.com/actions/runner-images/issues/12878
        # https://bugs.launchpad.net/ubuntu/+source/linux-signed-azure/+bug/2086741
        # https://github.com/actions/runner-images/blob/563ad669b646f6f3d68e17b9d83d4028806becb6/images/ubuntu/scripts/build/configure-apt-sources.sh#L16
      - name: Setup cross-compilation
        run: |

          if [[ $ImageOS == "ubuntu24" ]]; then
          cat >> deb822sources << EOF
          Types: deb
          URIs: mirror+file:/etc/apt/apt-mirrors.txt
          Suites: noble noble-updates noble-backports
          Components: main universe restricted multiverse
          Architectures: amd64 i386
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

          ## Ubuntu security updates. Aside from URIs and Suites,
          ## this should mirror your choices in the previous section.
          Types: deb
          URIs: mirror+file:/etc/apt/apt-mirrors.txt
          Suites: noble-security
          Components: main universe restricted multiverse
          Architectures: amd64 i386
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
        
          Types: deb
          URIs: http://azure.ports.ubuntu.com/ubuntu-ports/
          Suites: noble noble-updates noble-security
          Components: main
          Architectures: arm64 armhf
          EOF
  
          sudo mv deb822sources /etc/apt/sources.list.d/ubuntu.sources

          fi

          # sudo dpkg --add-architecture i386
          # sudo dpkg --add-architecture armhf
          sudo dpkg --add-architecture arm64
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq update

      - name: Configure non-verbose wget logging
        run: |

          cat >> $HOME/.wgetrc << EOF
          dot_bytes = 1024m
          quiet = on
          verbose = off
          EOF

      - name: Install NuttX dependencies
        run: |

          sudo apt-get -yq update
          # https://nuttx.apache.org/docs/latest/quickstart/install.html#prerequisites
          sudo apt-get -yq install \
          bison flex gettext texinfo libncurses5-dev libncursesw5-dev xxd \
          git gperf automake libtool pkg-config build-essential gperf genromfs \
          libgmp-dev libmpc-dev libmpfr-dev libisl-dev binutils-dev libelf-dev \
          libexpat1-dev gcc-multilib g++-multilib picocom u-boot-tools util-linux
          # https://nuttx.apache.org/docs/latest/quickstart/install.html#kconfig-frontend
          sudo apt-get -yq install kconfig-frontends

        # Extra dependencies specific to particular demos.
      - name: Install extra dependencies
        run: |

          # sim/alsa - https://github.com/apache/nuttx/pull/15918
          # https://github.com/apache/nuttx/blob/a84d263f094afc72a545d0cfcead88fd498947bf/tools/ci/docker/linux/Dockerfile#L335-L381
          sudo apt-get -yq install --no-install-recommends \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libc6:arm64 \
            zlib1g-dev:arm64 \
            genromfs \
            gettext \
            lib32z1-dev \
            libasound2-dev \
            libcurl4-openssl-dev \
            libmp3lame-dev \
            libmad0-dev \
            libncurses5-dev \
            libpulse-dev \
            libtinfo6 \
            libusb-1.0-0-dev libusb-1.0-0-dev:arm64 \
            libv4l-dev \
            libx11-dev libx11-dev:arm64 \
            libxext-dev libxext-dev:arm64 \
            linux-headers-generic \
            u-boot-tools \
            xxd \
            subversion \
            tclsh

      - name: Download NuttX
        run: |

          # https://nuttx.apache.org/docs/latest/quickstart/install.html#download-nuttx
          mkdir nuttxspace
          cd nuttxspace
          git clone -b cc_aarch64_linux --single-branch --depth 1 https://github.com/mars-low/nuttx.git nuttx
          git clone --depth 1 https://github.com/apache/nuttx-apps apps

      - name: Build NuttX examples for aarch64
        run: |

          cd nuttxspace/nuttx

          for f in boards/sim/sim/sim/configs/*;
          do
            config=$(basename $f)
            skip=true

            for d in "bluetooth" "bthcisock" "btuart" "usbdev" "usbhost";
            do
              echo "Check SIM config: if $d == $config then do not skip"
              if [[ "$config" == "$d" ]]; then
                skip=false
              fi
            done

            if [[ "$skip" == true ]]; then
              echo "Skipping SIM config $config"
              continue
            fi

            echo "Building SIM config $config"

            make distclean
            ./tools/configure.sh sim:$config
            kconfig-tweak --disable CONFIG_HOST_X86
            kconfig-tweak --disable CONFIG_HOST_X86_64
            kconfig-tweak --enable CONFIG_HOST_ARM64
            make -j 2 CROSSDEV=aarch64-linux-gnu-
            mkdir -p build/sim/aarch64/{bin,pac}/$config
            mv nuttx build/sim/aarch64/bin/$config
            mv nuttx.tgz build/sim/aarch64/pac/$config
          done

      - name: Build NuttX examples for x86_64
        run: |

          cd nuttxspace/nuttx

          for f in boards/sim/sim/sim/configs/*;
          do
            config=$(basename $f)
            skip=true

            for d in "bluetooth" "bthcisock" "btuart" "usbdev" "usbhost";
            do
              echo "Check SIM config: if $d == $config then do not skip"
              if [[ "$config" == "$d" ]]; then
                skip=false
              fi
            done

            if [[ "$skip" == true ]]; then
              echo "Skipping SIM config $config"
              continue
            fi

            echo "Building SIM config $config"

            make distclean
            ./tools/configure.sh sim:$config
            make -j 2
            mkdir -p build/sim/x86_64/{bin,pac}/$config
            mv nuttx build/sim/x86_64/bin/$config
            mv nuttx.tgz build/sim/x86_64/pac/$config
          done

      - uses: actions/upload-artifact@v4
        with:
          name: nuttx-binaries-x86_64-bin
          path: |
            nuttxspace/nuttx/build/sim/x86_64/bin/

      - uses: actions/upload-artifact@v4
        with:
          name: nuttx-binaries-x86_64-pac
          path: |
            nuttxspace/nuttx/build/sim/x86_64/pac/

      - uses: actions/upload-artifact@v4
        with:
          name: nuttx-binaries-aarch64-bin
          path: |
            nuttxspace/nuttx/build/sim/aarch64/bin/

      - uses: actions/upload-artifact@v4
        with:
          name: nuttx-binaries-aarch64-pac
          path: |
            nuttxspace/nuttx/build/sim/aarch64/pac/
