name: Tinyusb

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Build tinyusb examples
        run: |
          wget -nv https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi.tar.xz
          tar xf arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi.tar.xz
          export PATH=$PWD/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/bin:$PATH
          git clone https://github.com/hathach/tinyusb
          cd tinyusb
          python tools/get_deps.py nrf
          for dir in examples/device/*/; do (cd $dir && echo $dir && make BOARD=pca10056 all); done

      - uses: actions/upload-artifact@v4
        with:
          name: tinyusb-binaries
          # Maintain path hierarchy https://github.com/actions/upload-artifact/issues/174#issuecomment-2649189928
          path: |
            tinyusb/examples/device/**/*.elf
            tinyusb/.gitignore
