name: Zephyr

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Build Zephyr examples
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install --no-install-recommends ninja-build gperf ccache dfu-util device-tree-compiler python3-dev python3-venv python3-pip python3-setuptools python3-tk python3-wheel gcc-multilib g++-multilib libsdl2-dev libmagic1
          python3 -m venv zephyrproject/.venv
          source zephyrproject/.venv/bin/activate
          pip install west
          west init zephyrproject
          cd zephyrproject
          west update
          west zephyr-export
          west packages pip --install
          cd zephyr
          west sdk install
          west config build.dir-fmt "build/{board}/{app}"

          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/webusb
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/cdc_acm
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/audio/headphones_microphone
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/audio/headset
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/dfu
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/hid-mouse
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/hid-keyboard
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/shell
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/testusb
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/console
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/mass -- -DEXTRA_DTC_OVERLAY_FILE=ramdisk.overlay -DCONFIG_APP_MSC_STORAGE_RAM=y
          west build -p always -b nrf52840dk/nrf52840 samples/bluetooth/hci_usb
          west build -p always -b nrf52840dk/nrf52840 samples/net/zperf -- -DEXTRA_CONF_FILE=overlay-netusb.conf

      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            zephyrproject/zephyr/build/nrf52840dk/nrf52840/*/zephyr/zephyr.elf
