name: Zephyr

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Print apt sources
        run: |

          cat /etc/apt/sources.list.d/ubuntu.sources

        # https://github.com/actions/runner-images/issues/10901
        # https://github.com/actions/runner-images/issues/12878
        # https://bugs.launchpad.net/ubuntu/+source/linux-signed-azure/+bug/2086741
        # https://github.com/actions/runner-images/blob/563ad669b646f6f3d68e17b9d83d4028806becb6/images/ubuntu/scripts/build/configure-apt-sources.sh#L16
      - name: Setup cross-compilation
        run: |

          if [[ $ImageOS == "ubuntu24" ]]; then
          cat >> deb822sources << EOF
          Types: deb
          URIs: mirror+file:/etc/apt/apt-mirrors.txt
          Suites: noble noble-updates noble-backports
          Components: main universe restricted multiverse
          Architectures: amd64 i386
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

          ## Ubuntu security updates. Aside from URIs and Suites,
          ## this should mirror your choices in the previous section.
          Types: deb
          URIs: mirror+file:/etc/apt/apt-mirrors.txt
          Suites: noble-security
          Components: main universe restricted multiverse
          Architectures: amd64 i386
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
        
          Types: deb
          URIs: http://azure.ports.ubuntu.com/ubuntu-ports/
          Suites: noble noble-updates noble-security
          Components: main
          Architectures: arm64 armhf
          EOF
  
          sudo mv deb822sources /etc/apt/sources.list.d/ubuntu.sources

          fi

          sudo dpkg --add-architecture i386
          sudo dpkg --add-architecture armhf
          sudo dpkg --add-architecture arm64
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq update

      - name: Configure non-verbose wget logging
        run: |

          cat >> $HOME/.wgetrc << EOF
          dot_bytes = 1024m
          quiet = on
          verbose = off
          EOF

      - name: Install custom toolchains
        run: |

          # https://toolchains.bootlin.com
          wget https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--glibc--bleeding-edge-2025.08-1.tar.xz
          tar xf aarch64--glibc--bleeding-edge-2025.08-1.tar.xz
          # CROSS_COMPILE prefix: $GITHUB_WORKSPACE/aarch64--glibc--bleeding-edge-2025.08-1/bin/aarch64-buildroot-linux-gnu-
          wget https://toolchains.bootlin.com/downloads/releases/toolchains/armv6-eabihf/tarballs/armv6-eabihf--glibc--bleeding-edge-2025.08-1.tar.xz
          tar xf armv6-eabihf--glibc--bleeding-edge-2025.08-1.tar.xz
          # CROSS_COMPILE prefix: $GITHUB_WORKSPACE/armv6-eabihf--glibc--bleeding-edge-2025.08-1/bin/arm-buildroot-linux-gnueabihf-

      - name: Setup Zephyr
        run: |

          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install --no-install-recommends ninja-build gperf ccache dfu-util device-tree-compiler python3-dev python3-venv python3-pip python3-setuptools python3-tk python3-wheel gcc-multilib g++-multilib libsdl2-dev libmagic1
          # Note aboout gcc-multilib and g++-multilib:
          # https://github.com/zephyrproject-rtos/zephyr/blob/cb1b1212e4be5ade0b0cdd8a236b17245ba6fd25/boards/native/native_sim/doc/cross_compile.rst?plain=1#L38-L44
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq remove gcc-multilib g++-multilib
          # Install Linux Kernel Headers for development (linux-libc-dev):
          # https://github.com/zephyrproject-rtos/zephyr/pull/96582#issuecomment-3341557810
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install --no-install-recommends linux-libc-dev linux-libc-dev:i386 linux-libc-dev:armhf linux-libc-dev:arm64 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf

          python3 -m venv zephyrproject/.venv
          source zephyrproject/.venv/bin/activate
          pip install west
          west init zephyrproject
          cd zephyrproject
          west update
          west zephyr-export
          west packages pip --install
          cd zephyr
          west sdk install --gnu-toolchains arm-zephyr-eabi

      - name: Test cross-compilation
        run: |

          ARM_BUILDROOT_LINUX_GNUEABIHF_CC=$GITHUB_WORKSPACE/armv6-eabihf--glibc--bleeding-edge-2025.08-1/bin/arm-buildroot-linux-gnueabihf-
          AARCH64_BUILDROOT_LINUX_GNU_CC=$GITHUB_WORKSPACE/aarch64--glibc--bleeding-edge-2025.08-1/bin/aarch64-buildroot-linux-gnu-

          source zephyrproject/.venv/bin/activate
          cd zephyrproject/zephyr
          west config build.dir-fmt "build/test/{board}/{app}"

          west build -p -b native_sim//64 samples/bluetooth/bap_broadcast_assistant
          west build -p -b native_sim/native samples/bluetooth/bap_broadcast_assistant
          # Do not use /usr/bin/gcc-aarch64-linux-gnu- or /usr/bin/gcc-arm-linux-gnueabihf- due to sysroot issues:
          # https://groups.google.com/g/linux.debian.bugs.dist/c/S4eraIyuuzk
          # Instead use prebuilt toolchain with bundled sysroot.
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/dfu -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/dfu -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC

      - name: Build Zephyr nrf52840dk/nrf52840 examples
        run: |

          source zephyrproject/.venv/bin/activate
          cd zephyrproject/zephyr
          west config build.dir-fmt "build/{board}/{app}"

          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/cdc_acm
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/cdc_acm_bridge
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/console
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/dfu
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/hid-keyboard
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/hid-mouse
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/mass -- -DEXTRA_DTC_OVERLAY_FILE=ramdisk.overlay -DCONFIG_APP_MSC_STORAGE_RAM=y
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/midi
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/shell
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/testusb
          west build -p always -b nrf52840dk/nrf52840 -S video-sw-generator samples/subsys/usb/uvc
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/webusb
          west build -p always -b nrf52840dk/nrf52840 samples/bluetooth/hci_usb
          west build -p always -b nrf52840dk/nrf52840 samples/net/zperf -- -DEXTRA_CONF_FILE=overlay-usbd.conf

          west config build.dir-fmt "build/legacy/{board}/{app}"

          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/legacy/audio_headphones_microphone
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/legacy/audio_headset
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/legacy/cdc_acm
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/legacy/console
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/legacy/dfu
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/legacy/hci_usb
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/legacy/hid-mouse
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/legacy/mass
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/legacy/netusb
          west build -p always -b nrf52840dk/nrf52840 samples/subsys/usb/legacy/webusb

      - name: Build Zephyr nrf52840dongle/nrf52840 examples
        run: |

          source zephyrproject/.venv/bin/activate
          cd zephyrproject/zephyr
          west config build.dir-fmt "build/{board}/{app}"

          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/cdc_acm
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/cdc_acm_bridge
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/console
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/dfu
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/hid-keyboard
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/hid-mouse
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/mass -- -DEXTRA_DTC_OVERLAY_FILE=ramdisk.overlay -DCONFIG_APP_MSC_STORAGE_RAM=y
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/midi
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/shell
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/testusb
          west build -p always -b nrf52840dongle/nrf52840 -S video-sw-generator samples/subsys/usb/uvc
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/webusb
          west build -p always -b nrf52840dongle/nrf52840 samples/bluetooth/hci_usb
          west build -p always -b nrf52840dongle/nrf52840 samples/net/zperf -- -DEXTRA_CONF_FILE=overlay-usbd.conf

          west config build.dir-fmt "build/legacy/{board}/{app}"

          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/legacy/audio_headphones_microphone
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/legacy/audio_headset
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/legacy/cdc_acm
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/legacy/console
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/legacy/dfu
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/legacy/hci_usb
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/legacy/hid-mouse
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/legacy/mass
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/legacy/netusb
          west build -p always -b nrf52840dongle/nrf52840 samples/subsys/usb/legacy/webusb

      - name: Build Zephyr native_sim/native/64 examples for aarch64
        run: |

          AARCH64_BUILDROOT_LINUX_GNU_CC=$GITHUB_WORKSPACE/aarch64--glibc--bleeding-edge-2025.08-1/bin/aarch64-buildroot-linux-gnu-

          source zephyrproject/.venv/bin/activate
          cd zephyrproject/zephyr
          west config build.dir-fmt "build/aarch64/{board}/{app}"

          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/dfu -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/hid-keyboard -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/hid-mouse -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/mass -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC -DEXTRA_DTC_OVERLAY_FILE=ramdisk.overlay -DCONFIG_APP_MSC_STORAGE_RAM=y
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/shell -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/testusb -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 -S usbip-native-sim -S video-sw-generator samples/subsys/usb/uvc -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/webusb -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC

          west build -p -b native_sim//64 samples/bluetooth/bap_broadcast_assistant -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/bap_unicast_client -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/bap_unicast_server -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/beacon -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/broadcaster -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/bthome_sensor_template -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/cap_acceptor -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/cap_initiator -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/ccp_call_control_client -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/ccp_call_control_server -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/central -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/central_gatt_write -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/central_hr -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/central_ht -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/central_multilink -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/central_past -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/direct_adv -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/eddystone -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/extended_adv/advertiser -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/extended_adv/scanner -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/hap_ha -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/ibeacon -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/iso_broadcast -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/iso_central -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/iso_peripheral -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/iso_receive -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/l2cap_coc_acceptor -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/l2cap_coc_initiator -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/mtu_update/central -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/mtu_update/peripheral -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/observer -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/pbp_public_broadcast_sink -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/pbp_public_broadcast_source -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/periodic_adv -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/periodic_adv_conn -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/periodic_adv_rsp -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/periodic_sync -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/periodic_sync_conn -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/periodic_sync_rsp -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_accept_list -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_ans -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_csc -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_dis -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_esp -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_ets -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_gap_svc -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_gatt_write -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_hids -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_hr -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_ht -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_identity -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_nus -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_ots -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_past -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/peripheral_sc_only -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/scan_adv -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/tmap_bmr -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/tmap_bms -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/tmap_central -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC
          west build -p -b native_sim//64 samples/bluetooth/tmap_peripheral -- -DNATIVE_TARGET_HOST=aarch64 -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$AARCH64_BUILDROOT_LINUX_GNU_CC

      - name: Build Zephyr native_sim/native examples for arm
        run: |

          ARM_BUILDROOT_LINUX_GNUEABIHF_CC=$GITHUB_WORKSPACE/armv6-eabihf--glibc--bleeding-edge-2025.08-1/bin/arm-buildroot-linux-gnueabihf-

          source zephyrproject/.venv/bin/activate
          cd zephyrproject/zephyr
          west config build.dir-fmt "build/arm/{board}/{app}"

          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/dfu -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/hid-keyboard -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/hid-mouse -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/mass -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC -DEXTRA_DTC_OVERLAY_FILE=ramdisk.overlay -DCONFIG_APP_MSC_STORAGE_RAM=y
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/shell -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/testusb -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native -S usbip-native-sim -S video-sw-generator samples/subsys/usb/uvc -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/webusb -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC

          west build -p -b native_sim/native samples/bluetooth/bap_broadcast_assistant -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/bap_unicast_client -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/bap_unicast_server -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/beacon -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/broadcaster -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/bthome_sensor_template -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/cap_acceptor -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/cap_initiator -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/ccp_call_control_client -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/ccp_call_control_server -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/central -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/central_gatt_write -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/central_hr -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/central_ht -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/central_multilink -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/central_past -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/direct_adv -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/eddystone -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/extended_adv/advertiser -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/extended_adv/scanner -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/hap_ha -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/ibeacon -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/iso_broadcast -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/iso_central -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/iso_peripheral -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/iso_receive -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/l2cap_coc_acceptor -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/l2cap_coc_initiator -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/mtu_update/central -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/mtu_update/peripheral -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/observer -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/pbp_public_broadcast_sink -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/pbp_public_broadcast_source -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/periodic_adv -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/periodic_adv_conn -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/periodic_adv_rsp -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/periodic_sync -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/periodic_sync_conn -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/periodic_sync_rsp -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_accept_list -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_ans -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_csc -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_dis -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_esp -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_ets -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_gap_svc -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_gatt_write -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_hids -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_hr -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_ht -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_identity -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_nus -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_ots -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_past -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/peripheral_sc_only -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/scan_adv -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/tmap_bmr -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/tmap_bms -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/tmap_central -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/tmap_peripheral -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          # Extras (supported for 32-bit only)
          west build -p -b native_sim/native samples/bluetooth/mesh_demo -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC
          west build -p -b native_sim/native samples/bluetooth/mesh_provisioner -- -DNATIVE_TARGET_HOST=arm -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile -DCROSS_COMPILE=$ARM_BUILDROOT_LINUX_GNUEABIHF_CC

      - name: Build Zephyr native_sim/native/64 examples for x86_64
        run: |

          source zephyrproject/.venv/bin/activate
          cd zephyrproject/zephyr
          west config build.dir-fmt "build/x86_64/{board}/{app}"

          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/dfu
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/hid-keyboard
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/hid-mouse
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/mass -- -DEXTRA_DTC_OVERLAY_FILE=ramdisk.overlay -DCONFIG_APP_MSC_STORAGE_RAM=y
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/shell
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/testusb
          west build -p -b native_sim//64 -S usbip-native-sim -S video-sw-generator samples/subsys/usb/uvc
          west build -p -b native_sim//64 -S usbip-native-sim samples/subsys/usb/webusb

          west build -p -b native_sim//64 samples/bluetooth/bap_broadcast_assistant
          west build -p -b native_sim//64 samples/bluetooth/bap_unicast_client
          west build -p -b native_sim//64 samples/bluetooth/bap_unicast_server
          west build -p -b native_sim//64 samples/bluetooth/beacon
          west build -p -b native_sim//64 samples/bluetooth/broadcaster
          west build -p -b native_sim//64 samples/bluetooth/bthome_sensor_template
          west build -p -b native_sim//64 samples/bluetooth/cap_acceptor
          west build -p -b native_sim//64 samples/bluetooth/cap_initiator
          west build -p -b native_sim//64 samples/bluetooth/ccp_call_control_client
          west build -p -b native_sim//64 samples/bluetooth/ccp_call_control_server
          west build -p -b native_sim//64 samples/bluetooth/central
          west build -p -b native_sim//64 samples/bluetooth/central_gatt_write
          west build -p -b native_sim//64 samples/bluetooth/central_hr
          west build -p -b native_sim//64 samples/bluetooth/central_ht
          west build -p -b native_sim//64 samples/bluetooth/central_multilink
          west build -p -b native_sim//64 samples/bluetooth/central_past
          west build -p -b native_sim//64 samples/bluetooth/direct_adv
          west build -p -b native_sim//64 samples/bluetooth/eddystone
          west build -p -b native_sim//64 samples/bluetooth/extended_adv/advertiser
          west build -p -b native_sim//64 samples/bluetooth/extended_adv/scanner
          west build -p -b native_sim//64 samples/bluetooth/hap_ha
          west build -p -b native_sim//64 samples/bluetooth/ibeacon
          west build -p -b native_sim//64 samples/bluetooth/iso_broadcast
          west build -p -b native_sim//64 samples/bluetooth/iso_central
          west build -p -b native_sim//64 samples/bluetooth/iso_peripheral
          west build -p -b native_sim//64 samples/bluetooth/iso_receive
          west build -p -b native_sim//64 samples/bluetooth/l2cap_coc_acceptor
          west build -p -b native_sim//64 samples/bluetooth/l2cap_coc_initiator
          west build -p -b native_sim//64 samples/bluetooth/mtu_update/central
          west build -p -b native_sim//64 samples/bluetooth/mtu_update/peripheral
          west build -p -b native_sim//64 samples/bluetooth/observer
          west build -p -b native_sim//64 samples/bluetooth/pbp_public_broadcast_sink
          west build -p -b native_sim//64 samples/bluetooth/pbp_public_broadcast_source
          west build -p -b native_sim//64 samples/bluetooth/periodic_adv
          west build -p -b native_sim//64 samples/bluetooth/periodic_adv_conn
          west build -p -b native_sim//64 samples/bluetooth/periodic_adv_rsp
          west build -p -b native_sim//64 samples/bluetooth/periodic_sync
          west build -p -b native_sim//64 samples/bluetooth/periodic_sync_conn
          west build -p -b native_sim//64 samples/bluetooth/periodic_sync_rsp
          west build -p -b native_sim//64 samples/bluetooth/peripheral
          west build -p -b native_sim//64 samples/bluetooth/peripheral_accept_list
          west build -p -b native_sim//64 samples/bluetooth/peripheral_ans
          west build -p -b native_sim//64 samples/bluetooth/peripheral_csc
          west build -p -b native_sim//64 samples/bluetooth/peripheral_dis
          west build -p -b native_sim//64 samples/bluetooth/peripheral_esp
          west build -p -b native_sim//64 samples/bluetooth/peripheral_ets
          west build -p -b native_sim//64 samples/bluetooth/peripheral_gap_svc
          west build -p -b native_sim//64 samples/bluetooth/peripheral_gatt_write
          west build -p -b native_sim//64 samples/bluetooth/peripheral_hids
          west build -p -b native_sim//64 samples/bluetooth/peripheral_hr
          west build -p -b native_sim//64 samples/bluetooth/peripheral_ht
          west build -p -b native_sim//64 samples/bluetooth/peripheral_identity
          west build -p -b native_sim//64 samples/bluetooth/peripheral_nus
          west build -p -b native_sim//64 samples/bluetooth/peripheral_ots
          west build -p -b native_sim//64 samples/bluetooth/peripheral_past
          west build -p -b native_sim//64 samples/bluetooth/peripheral_sc_only
          west build -p -b native_sim//64 samples/bluetooth/scan_adv
          west build -p -b native_sim//64 samples/bluetooth/tmap_bmr
          west build -p -b native_sim//64 samples/bluetooth/tmap_bms
          west build -p -b native_sim//64 samples/bluetooth/tmap_central
          west build -p -b native_sim//64 samples/bluetooth/tmap_peripheral

      - name: Build Zephyr native_sim/native examples for x86
        run: |

          source zephyrproject/.venv/bin/activate
          cd zephyrproject/zephyr
          west config build.dir-fmt "build/x86/{board}/{app}"

          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/dfu
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/hid-keyboard
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/hid-mouse
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/mass -- -DEXTRA_DTC_OVERLAY_FILE=ramdisk.overlay -DCONFIG_APP_MSC_STORAGE_RAM=y
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/shell
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/testusb
          west build -p -b native_sim/native -S usbip-native-sim -S video-sw-generator samples/subsys/usb/uvc
          west build -p -b native_sim/native -S usbip-native-sim samples/subsys/usb/webusb

          west build -p -b native_sim/native samples/bluetooth/bap_broadcast_assistant
          west build -p -b native_sim/native samples/bluetooth/bap_unicast_client
          west build -p -b native_sim/native samples/bluetooth/bap_unicast_server
          west build -p -b native_sim/native samples/bluetooth/beacon
          west build -p -b native_sim/native samples/bluetooth/broadcaster
          west build -p -b native_sim/native samples/bluetooth/bthome_sensor_template
          west build -p -b native_sim/native samples/bluetooth/cap_acceptor
          west build -p -b native_sim/native samples/bluetooth/cap_initiator
          west build -p -b native_sim/native samples/bluetooth/ccp_call_control_client
          west build -p -b native_sim/native samples/bluetooth/ccp_call_control_server
          west build -p -b native_sim/native samples/bluetooth/central
          west build -p -b native_sim/native samples/bluetooth/central_gatt_write
          west build -p -b native_sim/native samples/bluetooth/central_hr
          west build -p -b native_sim/native samples/bluetooth/central_ht
          west build -p -b native_sim/native samples/bluetooth/central_multilink
          west build -p -b native_sim/native samples/bluetooth/central_past
          west build -p -b native_sim/native samples/bluetooth/direct_adv
          west build -p -b native_sim/native samples/bluetooth/eddystone
          west build -p -b native_sim/native samples/bluetooth/extended_adv/advertiser
          west build -p -b native_sim/native samples/bluetooth/extended_adv/scanner
          west build -p -b native_sim/native samples/bluetooth/hap_ha
          west build -p -b native_sim/native samples/bluetooth/ibeacon
          west build -p -b native_sim/native samples/bluetooth/iso_broadcast
          west build -p -b native_sim/native samples/bluetooth/iso_central
          west build -p -b native_sim/native samples/bluetooth/iso_peripheral
          west build -p -b native_sim/native samples/bluetooth/iso_receive
          west build -p -b native_sim/native samples/bluetooth/l2cap_coc_acceptor
          west build -p -b native_sim/native samples/bluetooth/l2cap_coc_initiator
          west build -p -b native_sim/native samples/bluetooth/mtu_update/central
          west build -p -b native_sim/native samples/bluetooth/mtu_update/peripheral
          west build -p -b native_sim/native samples/bluetooth/observer
          west build -p -b native_sim/native samples/bluetooth/pbp_public_broadcast_sink
          west build -p -b native_sim/native samples/bluetooth/pbp_public_broadcast_source
          west build -p -b native_sim/native samples/bluetooth/periodic_adv
          west build -p -b native_sim/native samples/bluetooth/periodic_adv_conn
          west build -p -b native_sim/native samples/bluetooth/periodic_adv_rsp
          west build -p -b native_sim/native samples/bluetooth/periodic_sync
          west build -p -b native_sim/native samples/bluetooth/periodic_sync_conn
          west build -p -b native_sim/native samples/bluetooth/periodic_sync_rsp
          west build -p -b native_sim/native samples/bluetooth/peripheral
          west build -p -b native_sim/native samples/bluetooth/peripheral_accept_list
          west build -p -b native_sim/native samples/bluetooth/peripheral_ans
          west build -p -b native_sim/native samples/bluetooth/peripheral_csc
          west build -p -b native_sim/native samples/bluetooth/peripheral_dis
          west build -p -b native_sim/native samples/bluetooth/peripheral_esp
          west build -p -b native_sim/native samples/bluetooth/peripheral_ets
          west build -p -b native_sim/native samples/bluetooth/peripheral_gap_svc
          west build -p -b native_sim/native samples/bluetooth/peripheral_gatt_write
          west build -p -b native_sim/native samples/bluetooth/peripheral_hids
          west build -p -b native_sim/native samples/bluetooth/peripheral_hr
          west build -p -b native_sim/native samples/bluetooth/peripheral_ht
          west build -p -b native_sim/native samples/bluetooth/peripheral_identity
          west build -p -b native_sim/native samples/bluetooth/peripheral_nus
          west build -p -b native_sim/native samples/bluetooth/peripheral_ots
          west build -p -b native_sim/native samples/bluetooth/peripheral_past
          west build -p -b native_sim/native samples/bluetooth/peripheral_sc_only
          west build -p -b native_sim/native samples/bluetooth/scan_adv
          west build -p -b native_sim/native samples/bluetooth/tmap_bmr
          west build -p -b native_sim/native samples/bluetooth/tmap_bms
          west build -p -b native_sim/native samples/bluetooth/tmap_central
          west build -p -b native_sim/native samples/bluetooth/tmap_peripheral
          # Extras (supported for 32-bit only)
          west build -p -b native_sim/native samples/bluetooth/mesh_demo
          west build -p -b native_sim/native samples/bluetooth/mesh_provisioner

      - uses: actions/upload-artifact@v4
        with:
          name: zephyr-binaries-nrf52840dk_nrf52840
          # Maintain path hierarchy https://github.com/actions/upload-artifact/issues/174#issuecomment-2649189928
          path: |
            zephyrproject/zephyr/.gitignore
            zephyrproject/zephyr/build/legacy/nrf52840dk/nrf52840/**/zephyr/zephyr.elf
            zephyrproject/zephyr/build/nrf52840dk/nrf52840/**/zephyr/zephyr.elf

      - uses: actions/upload-artifact@v4
        with:
          name: zephyr-binaries-nrf52840dongle_nrf52840
          # Maintain path hierarchy https://github.com/actions/upload-artifact/issues/174#issuecomment-2649189928
          path: |
            zephyrproject/zephyr/.gitignore
            zephyrproject/zephyr/build/legacy/nrf52840dongle/nrf52840/**/zephyr/zephyr.elf
            zephyrproject/zephyr/build/nrf52840dongle/nrf52840/**/zephyr/zephyr.elf

      - uses: actions/upload-artifact@v4
        with:
          name: zephyr-binaries-native_sim-aarch64
          path: |
            zephyrproject/zephyr/build/aarch64/**/zephyr/zephyr.exe

      - uses: actions/upload-artifact@v4
        with:
          name: zephyr-binaries-native_sim-arm
          path: |
            zephyrproject/zephyr/build/arm/**/zephyr/zephyr.exe

      - uses: actions/upload-artifact@v4
        with:
          name: zephyr-binaries-native_sim-x86_64
          path: |
            zephyrproject/zephyr/build/x86_64/**/zephyr/zephyr.exe

      - uses: actions/upload-artifact@v4
        with:
          name: zephyr-binaries-native_sim-x86
          path: |
            zephyrproject/zephyr/build/x86/**/zephyr/zephyr.exe
